{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.enaium.ja-grater",
    "module": "ja-grater",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ja-grater-1.3.0.jar",
          "url": "ja-grater-1.3.0.jar",
          "size": 12257,
          "sha512": "2e7e4c8478d36e4d466b2f3d1b9c2851886a44409a853cc856f2b10ab6061aa955475bb30745561c2594b59827b67c24871627f3cecd58e73d70d1a8538c5ba6",
          "sha256": "90872aaf2d8e0d0dbeb73e4b5693610b18f2e2555706de65e41ce4f24d1b0eb4",
          "sha1": "01f9eaa58e27ccea7a10d2683b2778ae28a347e6",
          "md5": "3873bd24e1f7bc4c1a848bf6a9364fe1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja-grater-1.3.0.jar",
          "url": "ja-grater-1.3.0.jar",
          "size": 12257,
          "sha512": "2e7e4c8478d36e4d466b2f3d1b9c2851886a44409a853cc856f2b10ab6061aa955475bb30745561c2594b59827b67c24871627f3cecd58e73d70d1a8538c5ba6",
          "sha256": "90872aaf2d8e0d0dbeb73e4b5693610b18f2e2555706de65e41ce4f24d1b0eb4",
          "sha1": "01f9eaa58e27ccea7a10d2683b2778ae28a347e6",
          "md5": "3873bd24e1f7bc4c1a848bf6a9364fe1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ja-grater-1.3.0-sources.jar",
          "url": "ja-grater-1.3.0-sources.jar",
          "size": 6457,
          "sha512": "8948c791a627bda090e66919e3609fd7e97dce4897d84f0cac3460ad7446b0d4f634a4a547b3c584bb62d9a90360034286bc5b479f6dd57f7d91273ca89a70d8",
          "sha256": "b60a0871c4570b2d4c7db3260bc8ce3d96e0000a7480a44db77cfbd98b2ca260",
          "sha1": "b9e2a6653225d7ca956485f3d2423bef4d801ea8",
          "md5": "a328aa7dc71f3155dcc3ec28b45900b2"
        }
      ]
    }
  ]
}
