{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.enaium.humblemc",
    "module": "HumbleGradle",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HumbleGradle-1.1.0.jar",
          "url": "HumbleGradle-1.1.0.jar",
          "size": 43257,
          "sha512": "517f8440a97532cc970725ae20bc28922b9cc9ecf2c0d5a4f63f619f2fa0ab1932c03ee0d8a9807089f05903d0ff0d3c0e0e357cddba5c11d300cd0f320c7726",
          "sha256": "c3e618c228d7292ffb29272b9162b9b5c175dc12a14c3f5069f94dcfa1b246e5",
          "sha1": "0e42aef5f31b52ae20456ca98b58ad8a6fb7d044",
          "md5": "32c48ee421c53eaeea02ada0919eb5c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "HumbleGradle-1.1.0.jar",
          "url": "HumbleGradle-1.1.0.jar",
          "size": 43257,
          "sha512": "517f8440a97532cc970725ae20bc28922b9cc9ecf2c0d5a4f63f619f2fa0ab1932c03ee0d8a9807089f05903d0ff0d3c0e0e357cddba5c11d300cd0f320c7726",
          "sha256": "c3e618c228d7292ffb29272b9162b9b5c175dc12a14c3f5069f94dcfa1b246e5",
          "sha1": "0e42aef5f31b52ae20456ca98b58ad8a6fb7d044",
          "md5": "32c48ee421c53eaeea02ada0919eb5c3"
        }
      ]
    }
  ]
}
