{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.enaium.humblemc",
    "module": "HumbleLoader",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "HumbleLoader-1.0.0.jar",
          "url": "HumbleLoader-1.0.0.jar",
          "size": 6539,
          "sha512": "a7630ea69340a1245148fc651324d84a21022ca457315594b5ce757f58b4825986e945c85f43647bf27aa1af4d8e6ac95dad97d94633f5d4db878a045670f044",
          "sha256": "1159f5ad53f4a6eadfe7a2adf4ecd2fe03da229a325b622aca5e7fd24c7c2069",
          "sha1": "e9b58952d2b9fcf1c5ed5749f695827b650487af",
          "md5": "ebe47e5d07eaaedec8d383c01b5e2ef6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cn.enaium",
          "module": "launchwrapper",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.spongepowered",
          "module": "mixin",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.mojang",
          "module": "patchy",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "oshi-project",
          "module": "oshi-core",
          "version": {
            "requires": "1.1"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "platform",
          "version": {
            "requires": "3.4.0"
          }
        },
        {
          "group": "com.ibm.icu",
          "module": "icu4j",
          "version": {
            "requires": "66.1"
          }
        },
        {
          "group": "com.mojang",
          "module": "javabridge",
          "version": {
            "requires": "1.0.22"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.3"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-all",
          "version": {
            "requires": "4.1.25.Final"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "21.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.5"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.5"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.10"
          }
        },
        {
          "group": "net.java.jinput",
          "module": "jinput",
          "version": {
            "requires": "2.0.5"
          }
        },
        {
          "group": "net.java.jutils",
          "module": "jutils",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "brigadier",
          "version": {
            "requires": "1.0.17"
          }
        },
        {
          "group": "com.mojang",
          "module": "datafixerupper",
          "version": {
            "requires": "4.0.26"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.mojang",
          "module": "authlib",
          "version": {
            "requires": "2.1.28"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.3.3"
          }
        },
        {
          "group": "commons-logging",
          "module": "commons-logging",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpcore",
          "version": {
            "requires": "4.3.2"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.2.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-jemalloc",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-openal",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-glfw",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-stb",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-tinyfd",
          "version": {
            "requires": "3.2.2"
          }
        },
        {
          "group": "com.mojang",
          "module": "text2speech",
          "version": {
            "requires": "1.11.3"
          }
        },
        {
          "group": "ca.weblite",
          "module": "java-objc-bridge",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "HumbleLoader-1.0.0.jar",
          "url": "HumbleLoader-1.0.0.jar",
          "size": 6539,
          "sha512": "a7630ea69340a1245148fc651324d84a21022ca457315594b5ce757f58b4825986e945c85f43647bf27aa1af4d8e6ac95dad97d94633f5d4db878a045670f044",
          "sha256": "1159f5ad53f4a6eadfe7a2adf4ecd2fe03da229a325b622aca5e7fd24c7c2069",
          "sha1": "e9b58952d2b9fcf1c5ed5749f695827b650487af",
          "md5": "ebe47e5d07eaaedec8d383c01b5e2ef6"
        }
      ]
    }
  ]
}
