{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.enaium.proxy-launcher",
    "module": "proxy-launcher",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0.jar",
          "url": "proxy-launcher-1.0.0.jar",
          "size": 10893,
          "sha512": "fd2fea860074025d59f9dd9332a82e311f051ed1d9164ded7a6ee8e3a8f0eb6925c3069c532b3fa4f2e672851106f04be742ec7e25bff489c39e76da76f172c5",
          "sha256": "75ead183281a763c42aeeec98f91ea301a2a66f5b645e42745406fc2c4da5eb2",
          "sha1": "5a0b6b2473ef8db1064b3f5b7a99bc1201baf31f",
          "md5": "d64c2f70f90f404624058108d5634542"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.monkeywie",
          "module": "proxyee",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "proxy-launcher-1.0.0.jar",
          "url": "proxy-launcher-1.0.0.jar",
          "size": 10893,
          "sha512": "fd2fea860074025d59f9dd9332a82e311f051ed1d9164ded7a6ee8e3a8f0eb6925c3069c532b3fa4f2e672851106f04be742ec7e25bff489c39e76da76f172c5",
          "sha256": "75ead183281a763c42aeeec98f91ea301a2a66f5b645e42745406fc2c4da5eb2",
          "sha1": "5a0b6b2473ef8db1064b3f5b7a99bc1201baf31f",
          "md5": "d64c2f70f90f404624058108d5634542"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0-all.jar",
          "url": "proxy-launcher-1.0.0-all.jar",
          "size": 401067,
          "sha512": "ae07777960c613c618dfed3c73b799476b765bfcafba5e03e50d722b88869d12d385d97a26f65cda3613593ad59053ab1191c04d462e84621e718907e05af493",
          "sha256": "d6d14f533c6da519a90ed17be427f0852a07efae673c3cf8259eccde1a56f50e",
          "sha1": "ee0208048dfdac95ff5a585e32845b21b7a21797",
          "md5": "2d82c5464599da52085ca7cdcf2b4de8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0-sources.jar",
          "url": "proxy-launcher-1.0.0-sources.jar",
          "size": 4921,
          "sha512": "506b903af0622d59d9c611c724c118b03e0729a04ba61a3020bd26382a3a00f8f69c575f7bbc6b24512658ce8bf343c46863a8be866c18196f28a74766105e2c",
          "sha256": "e970efc8fd494045592ecbfa1c58a3214477083ed488a551e022e1e160f01cf9",
          "sha1": "7c1dd07f716cc6ca3afd6602c39083e3a6042476",
          "md5": "59e66c09840c62e2a9b8426cc02116a4"
        }
      ]
    }
  ]
}
