{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.enaium.proxy-launcher",
    "module": "proxy-launcher",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0.jar",
          "url": "proxy-launcher-1.0.0.jar",
          "size": 10893,
          "sha512": "85dbb832d0639d97fac7db70919d3ad29d205173b699647d6c4517afe79408ce7ced7e625d53d33ce3222fa69eeafdace2f125aa4015ce512fb9f9c9b97f6d2b",
          "sha256": "b5d87da29d948cf8cbd542db04d916ff5175a84da8bea5e64fea79b97eb1b8fa",
          "sha1": "fb0176947a3a5ca8bbb1cc9c7e2c06e197f0ce93",
          "md5": "0485dfc34eb8db0e51c0054652cb829e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.github.monkeywie",
          "module": "proxyee",
          "version": {
            "requires": "1.5.4"
          }
        }
      ],
      "files": [
        {
          "name": "proxy-launcher-1.0.0.jar",
          "url": "proxy-launcher-1.0.0.jar",
          "size": 10893,
          "sha512": "85dbb832d0639d97fac7db70919d3ad29d205173b699647d6c4517afe79408ce7ced7e625d53d33ce3222fa69eeafdace2f125aa4015ce512fb9f9c9b97f6d2b",
          "sha256": "b5d87da29d948cf8cbd542db04d916ff5175a84da8bea5e64fea79b97eb1b8fa",
          "sha1": "fb0176947a3a5ca8bbb1cc9c7e2c06e197f0ce93",
          "md5": "0485dfc34eb8db0e51c0054652cb829e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0-all.jar",
          "url": "proxy-launcher-1.0.0-all.jar",
          "size": 401067,
          "sha512": "bc3a8f0c7b829e82113068506fb813df7dc5544f3e60710b39a91e1e098274ee65dec9c010ce76a29b39866af07c8c1b8d1efa58709ee924203d10b9f7db9bb1",
          "sha256": "54c833c74e8ceba7a0b732ca2903b336b3fdbcc86654f6911c18b7fef46edda5",
          "sha1": "f969d501479e189d9470fb7d021c2978287e50fe",
          "md5": "f2cdb29367beb83294ffa7f257bb99fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "proxy-launcher-1.0.0-sources.jar",
          "url": "proxy-launcher-1.0.0-sources.jar",
          "size": 4921,
          "sha512": "506b903af0622d59d9c611c724c118b03e0729a04ba61a3020bd26382a3a00f8f69c575f7bbc6b24512658ce8bf343c46863a8be866c18196f28a74766105e2c",
          "sha256": "e970efc8fd494045592ecbfa1c58a3214477083ed488a551e022e1e160f01cf9",
          "sha1": "7c1dd07f716cc6ca3afd6602c39083e3a6042476",
          "md5": "59e66c09840c62e2a9b8426cc02116a4"
        }
      ]
    }
  ]
}
